#!/bin/bash

# DDO IAM User Setup Script (Bash)
# Creates an IAM user for the DDO application with appropriate permissions
#
# Prerequisites:
# - AWS CLI installed and configured (aws configure)
# - IAM permissions to create users and access keys
# - Run setup-cognito.sh first to create the policy
#
# Usage:
#   chmod +x scripts/aws/setup-iam-user.sh
#   ./scripts/aws/setup-iam-user.sh
#
# Or with custom values:
#   IAM_USER_NAME="my-app-user" ./scripts/aws/setup-iam-user.sh

set -e

# Configuration
USER_NAME="${IAM_USER_NAME:-ddo-app-user}"
POLICY_NAME="${IAM_POLICY_NAME:-ddo-cognito-policy}"

echo "============================================"
echo "  Digital DevOps - IAM User Setup Script"
echo "============================================"
echo ""
echo "Configuration:"
echo "  User Name:   $USER_NAME"
echo "  Policy Name: $POLICY_NAME"
echo ""

# Check if AWS CLI is installed
if ! command -v aws &> /dev/null; then
    echo "ERROR: AWS CLI is not installed. Please install it first."
    echo "  https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"
    exit 1
fi

# Check AWS credentials
echo "Checking AWS credentials..."
if ! aws sts get-caller-identity &> /dev/null; then
    echo "ERROR: AWS credentials not configured. Run 'aws configure' first."
    exit 1
fi

ACCOUNT_ID=$(aws sts get-caller-identity --query Account --output text)
echo "  AWS Account: $ACCOUNT_ID"
echo ""

# Step 1: Check if policy exists
echo "Step 1: Checking for IAM policy..."

POLICY_ARN=$(aws iam list-policies --scope Local --query "Policies[?PolicyName=='$POLICY_NAME'].Arn" --output text)

if [ -z "$POLICY_ARN" ]; then
    echo "  ERROR: Policy '$POLICY_NAME' not found."
    echo "  Please run setup-cognito.sh first to create the policy."
    exit 1
fi

echo "  Found policy: $POLICY_ARN"

# Step 2: Create IAM User
echo ""
echo "Step 2: Creating IAM user..."

if aws iam get-user --user-name "$USER_NAME" &> /dev/null; then
    echo "  User '$USER_NAME' already exists"
else
    aws iam create-user --user-name "$USER_NAME" > /dev/null
    echo "  Created user: $USER_NAME"
fi

# Step 3: Attach policy to user
echo ""
echo "Step 3: Attaching policy to user..."

aws iam attach-user-policy --user-name "$USER_NAME" --policy-arn "$POLICY_ARN" 2>/dev/null || true
echo "  Attached policy: $POLICY_NAME"

# Step 4: Create access keys
echo ""
echo "Step 4: Creating access keys..."

# Check existing access keys
KEY_COUNT=$(aws iam list-access-keys --user-name "$USER_NAME" --query 'length(AccessKeyMetadata)' --output text)

if [ "$KEY_COUNT" -ge 2 ]; then
    echo "  WARNING: User already has 2 access keys (maximum)."
    echo "  You can delete an old key with:"
    echo "    aws iam delete-access-key --user-name $USER_NAME --access-key-id <KEY_ID>"
    echo ""
    echo "  Existing keys:"
    aws iam list-access-keys --user-name "$USER_NAME" --query 'AccessKeyMetadata[*].[AccessKeyId,CreateDate,Status]' --output text | while read -r key_id create_date status; do
        echo "    - $key_id (Created: $create_date, Status: $status)"
    done

    ACCESS_KEY_ID="EXISTING_KEY_CHECK_AWS_CONSOLE"
    SECRET_ACCESS_KEY="EXISTING_KEY_CHECK_AWS_CONSOLE"
else
    # Create new access key
    KEY_RESULT=$(aws iam create-access-key --user-name "$USER_NAME" --output json)
    ACCESS_KEY_ID=$(echo "$KEY_RESULT" | grep -o '"AccessKeyId": "[^"]*"' | cut -d'"' -f4)
    SECRET_ACCESS_KEY=$(echo "$KEY_RESULT" | grep -o '"SecretAccessKey": "[^"]*"' | cut -d'"' -f4)

    echo "  Access Key ID: $ACCESS_KEY_ID"
    echo "  Secret Access Key: [HIDDEN - see .env.iam file]"
fi

# Step 5: Generate output file
echo ""
echo "Step 5: Generating configuration..."

ENV_FILE=".env.iam"
cat > "$ENV_FILE" <<EOF
# ==============================================
# AWS IAM User Credentials
# Generated by setup-iam-user.sh on $(date)
# ==============================================

# IAM User: $USER_NAME
# Policy: $POLICY_ARN

AWS_ACCESS_KEY_ID=$ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$SECRET_ACCESS_KEY

# ==============================================
# INSTRUCTIONS:
# 1. Copy these values to your .env file
# 2. IMPORTANT: Keep these credentials secure!
# 3. Never commit this file to version control
# 4. Delete this file after copying the values
# ==============================================
EOF

echo "  Credentials saved to: $ENV_FILE"

# Summary
echo ""
echo "============================================"
echo "  Setup Complete!"
echo "============================================"
echo ""
echo "Resources Created:"
echo "  - IAM User:   $USER_NAME"
echo "  - Policy:     $POLICY_NAME"
if [ "$ACCESS_KEY_ID" != "EXISTING_KEY_CHECK_AWS_CONSOLE" ]; then
    echo "  - Access Key: $ACCESS_KEY_ID"
fi
echo ""
echo "Next Steps:"
echo "  1. Copy AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY from .env.iam to .env"
echo "  2. Delete .env.iam after copying (for security)"
echo "  3. Verify SES email/domain in AWS Console"
echo "  4. Run: npx prisma migrate dev"
echo "  5. Restart your dev server"
echo ""
echo "Security Reminder:"
echo "  - Never commit AWS credentials to git"
echo "  - .env and .env.iam should be in .gitignore"
echo "  - Rotate keys periodically"
echo ""

# Verify .gitignore includes .env files
if [ -f ".gitignore" ]; then
    if ! grep -q "\.env" .gitignore; then
        echo "WARNING: .env may not be in .gitignore!"
        echo "  Add these lines to .gitignore:"
        echo "    .env"
        echo "    .env.*"
        echo "    !.env.example"
    fi
fi
